### PR TITLE
UI migrated to Angular Material and Latest Angular version 12

### PR DESCRIPTION
**Pull request by raj-itpc**
@kens-aais I have not deleted old folders (openidl-ui, openidl-carrier-ui and openidl-common-ui) as I am waiting for docker files and shell script to be updated so that it can pick build files from new folders. This PR includes changes for 3 angular projects.

### CODE REVIEW

**Comment by kens-aais** [comment]
@raj-itpc 
How do I test this locally?  I haven't worked with an angular workspace before.
We should update the readme.md file to reflect these instructions as well.

**Comment by raj-itpc** [comment]
@kens-aais I have added developer-guide.md file inside openidl-ui-workspace folder. Please check it here https://github.com/openidl-org/openidl-main/blob/raj-workspace/openidl-ui-workspace/developer-guide.md

**Comment by kens-aais** [comment]
The developer-guide.md should at least be pointed to from the readme.md
The current readme.md file is generic and should be updated.  AAIS can do this.

**Review by kens-aais — COMMENTED** [review]
I am not able to follow the developer-guide.md
the main readme.md file in the workspace folder should be updated to be less generic and point to the developer-guide.md if not just incorporate it.

**Comment by raj-itpc** [comment]
@kens-aais I have updated **openidl-ui-workspace\README.md** and **openidl-ui-workspace\developer-guide.md** files according to newly added commands.

**Comment by raj-itpc** [comment]
Ken

I have updated the readme document in the branch raj-workspace which includes build commands for the openidl-carrier-ui project. Please review and let me know me if you have any question.

Thanks
Raj

**Comment by raj-itpc** [comment]
@kens-aais Please review new changes and let me know if you have any questions.

**Comment by kens-aais** [comment]
I am trying to run it.  My days have been really filled with meetings so, unfortunately, I haven't been able to get everything going.  I made a cosmetic change and pushed it.  I changed "regulator" to "aais" as that is a better name for that node.

**Comment by kens-aais** [comment]
I get an error trying to run npm run start:aais
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/kennethwsayers/Development/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/kennethwsayers/Development/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kennethwsayers/.npm/_logs/2021-08-05T12_57_47_515Z-debug.log

**Comment by raj-itpc** [comment]
@kens-aais run all commands from inside openidl-ui-workspace folder

**Comment by kens-aais** [comment]
duh, yeah, i checked that and thought i was.  Ok. now i have to set up the config files.  Thanks and sorry for stupidity.

**Comment by kens-aais** [comment]
Raj, when running i get this message.
When running locally, make sure to create a file *localdev-config.json* in the root directory. See config.template.json for an example of a configuration file.

But there is no such file config.template.json that I can find.

**Comment by raj-itpc** [comment]
@kens-aais create local-appid-config.json file inside the config folder. That error message is coming from express code and it's not in the scope.
image

**Comment by kens-aais** [comment]
Now receiving an error getting the token:

WARNING: No configurations found in configuration directory:/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
[2021-08-05T11:24:35.912] [INFO] appid-sdk - Initialized
[2021-08-05T11:24:36.224] [INFO] ibm-cloud-env - Initializing with /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/config/mappings.json
[2021-08-05T11:24:36.229] [DEBUG] server - setting up app: registering routes, middleware...
[2021-08-05T11:24:36.230] [INFO] server - credential info
[2021-08-05T11:24:36.230] [INFO] server - {
  apikey: '0rawWuUPVlMLhcXMCjlyB6BI4RR4nn-dsIuj_myDrqpQ',
  appidServiceEndpoint: 'https://us-east.appid.cloud.ibm.com',
  clientId: '7ad632d8-abdc-448d-8029-91eeac0ae64e',
  discoveryEndpoint: 'https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92/.well-known/openid-configuration',
  iam_apikey_description: 'Auto-generated for key 7ad632d8-abdc-448d-8029-91eeac0ae64e',
  iam_apikey_name: 'stage-aais-AppID-ServiceKey',
  iam_role_crn: 'crn:v1:bluemix:public:iam::::serviceRole:Manager',
  iam_serviceid_crn: 'crn:v1:bluemix:public:iam-identity::a/361c80aeecd44412b23a7f1bc4ae580f::serviceid:ServiceId-a55b19de-13b7-429e-bd81-0150c4e98efa',
  managementUrl: 'https://us-east.appid.cloud.ibm.com/management/v4/d0649a19-cf64-4e36-897b-0338cf89fe92',
  oauthServerUrl: 'https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92',
  profilesUrl: 'https://us-east.appid.cloud.ibm.com',
  secret: 'ZGRiZTZjM2UtMmQyNS00NzU4LWI0NjEtODhjNDZlMDM2ZDNi',
  tenantId: 'd0649a19-cf64-4e36-897b-0338cf89fe92',
  version: 4,
  callerId: '7ad632d8-abdc-448d-8029-91eeac0ae64e'
}
[2021-08-05T11:24:36.231] [INFO] appid-WebAppStrategy-config - clientId 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T11:24:36.232] [INFO] appid-WebAppStrategy-config - tenantId d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:24:36.232] [INFO] appid-WebAppStrategy-config - secret [CANNOT LOG SECRET]
[2021-08-05T11:24:36.232] [INFO] appid-WebAppStrategy-config - oauthServerUrl https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:24:36.232] [INFO] appid-WebAppStrategy-config - redirectUri http://localhost:3000/ibm/bluemix/appid/callback
[2021-08-05T11:24:36.232] [INFO] appid-user profile config-config - oauthServerUrl https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:24:36.233] [INFO] appid-user profile config-config - profilesUrl https://us-east.appid.cloud.ibm.com
[2021-08-05T11:24:36.233] [INFO] appid-user-manager - profilesUrl https://us-east.appid.cloud.ibm.com
[2021-08-05T11:24:36.233] [INFO] appid-user-manager - oauthServerUrl https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:24:36.234] [INFO] appid-APIStrategy-config - oauthServerUrl https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:24:36.242] [DEBUG] server - setting up app: initializing passport
App started listening at  8080
[2021-08-05T11:51:16.186] [ERROR] appid-webapp-strategy - Failed to obtain tokens :: 400 {"error":"invalid_grant","error_description":"The email or password that you entered is incorrect.","cdErrorCode":"USER_NOT_FOUND"}
[2021-08-05T11:52:19.440] [INFO] appid-public-key-util - Public keys updated
[2021-08-05T11:52:19.444] [INFO] appid-token-util - token ver: 4
[2021-08-05T11:52:19.444] [INFO] appid-token-util - token version is valid
[2021-08-05T11:52:19.444] [INFO] appid-token-util - token aud: 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T11:52:19.813] [INFO] appid-token-util - token iss: https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:52:19.813] [INFO] appid-token-util - token ver: 4
[2021-08-05T11:52:19.813] [INFO] appid-token-util - token version is valid
[2021-08-05T11:52:19.814] [INFO] appid-token-util - token aud: 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T11:52:19.815] [INFO] appid-token-util - token iss: https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:52:20.305] [INFO] appid-TokenManager-config - clientId 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T11:52:20.305] [INFO] appid-TokenManager-config - secret [CANNOT LOG SECRET]
[2021-08-05T11:52:20.305] [INFO] appid-TokenManager-config - oauthServerUrl https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T11:52:20.663] [INFO] appid-token-util - token ver: 4
[2021-08-05T11:52:20.663] [INFO] appid-token-util - token version is valid
[2021-08-05T11:52:20.663] [INFO] appid-token-util - token aud: 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T11:52:20.932] [INFO] appid-token-util - token iss: https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
Error:  Error: Invalid URI "/block-explorer"
    at Request.init (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:273:31)
    at new Request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:127:8)
    at request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/index.js:53:10)
    at Object.common.handleRequest (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:58:5)
    at common.getBlockHistory (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:166:16)
    at Layer.handle [as handle_request] (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/route.js:137:13)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-common-ui/server/middlewares/api-auth-handler.js:103:9
    at ApiStrategy.strategy.success (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/passport/lib/middleware/authenticate.js:219:18)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/ibmcloud-appid/lib/strategies/api-strategy.js:152:16
queryString: status=DRAFT&version=latest&startIndex=0&pageSize=15&
Error:  Error: Invalid URI "/list-data-calls-by-criteria?status=DRAFT&version=latest&startIndex=0&pageSize=15&"
    at Request.init (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:273:31)
    at new Request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:127:8)
    at request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/index.js:53:10)
    at Object.common.handleRequest (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:58:5)
    at common.getDataCalls (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:138:16)
    at Layer.handle [as handle_request] (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/route.js:137:13)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-common-ui/server/middlewares/api-auth-handler.js:103:9
    at ApiStrategy.strategy.success (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/passport/lib/middleware/authenticate.js:219:18)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/ibmcloud-appid/lib/strategies/api-strategy.js:152:16

**Comment by kens-aais** [comment]
some kind of issue with user id perhaps, i'll double check configs etc

**Comment by raj-itpc** [comment]
@kens-aais sent you the mail with config details. You can delete the error message comment as it contains service details.

**Comment by kens-aais** [comment]
Your config was the same as mine.  Still replaced and still have the same problem:

[2021-08-05T14:09:28.239] [INFO] appid-public-key-util - Public keys updated
[2021-08-05T14:09:28.243] [INFO] appid-token-util - token ver: 4
[2021-08-05T14:09:28.243] [INFO] appid-token-util - token version is valid
[2021-08-05T14:09:28.243] [INFO] appid-token-util - token aud: 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T14:09:28.611] [INFO] appid-token-util - token iss: https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T14:09:28.611] [INFO] appid-token-util - token ver: 4
[2021-08-05T14:09:28.611] [INFO] appid-token-util - token version is valid
[2021-08-05T14:09:28.611] [INFO] appid-token-util - token aud: 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T14:09:28.611] [INFO] appid-token-util - token iss: https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T14:09:29.059] [INFO] appid-TokenManager-config - clientId 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T14:09:29.059] [INFO] appid-TokenManager-config - secret [CANNOT LOG SECRET]
[2021-08-05T14:09:29.059] [INFO] appid-TokenManager-config - oauthServerUrl https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
[2021-08-05T14:09:29.401] [INFO] appid-token-util - token ver: 4
[2021-08-05T14:09:29.401] [INFO] appid-token-util - token version is valid
[2021-08-05T14:09:29.401] [INFO] appid-token-util - token aud: 7ad632d8-abdc-448d-8029-91eeac0ae64e
[2021-08-05T14:09:29.706] [INFO] appid-token-util - token iss: https://us-east.appid.cloud.ibm.com/oauth/v4/d0649a19-cf64-4e36-897b-0338cf89fe92
Error:  Error: Invalid URI "/block-explorer"
    at Request.init (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:273:31)
    at new Request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:127:8)
    at request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/index.js:53:10)
    at Object.common.handleRequest (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:58:5)
    at common.getBlockHistory (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:166:16)
    at Layer.handle [as handle_request] (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/route.js:137:13)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-common-ui/server/middlewares/api-auth-handler.js:103:9
    at ApiStrategy.strategy.success (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/passport/lib/middleware/authenticate.js:219:18)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/ibmcloud-appid/lib/strategies/api-strategy.js:152:16
queryString: status=DRAFT&version=latest&startIndex=0&pageSize=15&
Error:  Error: Invalid URI "/list-data-calls-by-criteria?status=DRAFT&version=latest&startIndex=0&pageSize=15&"
    at Request.init (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:273:31)
    at new Request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/request.js:127:8)
    at request (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/request/index.js:53:10)
    at Object.common.handleRequest (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:58:5)
    at common.getDataCalls (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-ui/server/controllers/common.js:138:16)
    at Layer.handle [as handle_request] (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/express/lib/router/route.js:137:13)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/projects/openidl-common-ui/server/middlewares/api-auth-handler.js:103:9
    at ApiStrategy.strategy.success (/Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/passport/lib/middleware/authenticate.js:219:18)
    at /Users/kennethwsayers/Development/linux-foundation/branches/raj-workspace/openidl-main-raj-workspace/openidl-ui-workspace/node_modules/ibmcloud-appid/lib/strategies/api-strategy.js:152:16

**Comment by kens-aais** [comment]
I think i know what the problem is.  I need to point to the data call app in the ibm cloud.  Trying again now.

**Comment by kens-aais** [comment]
got it, working now!

**Comment by kens-aais** [comment]
so, it looks pretty good.  This is a pull request into develop.  Should this go directly there or be merged with other branches before going into dev?

**Comment by raj-itpc** [comment]
@kens-aais merge it into develop and please **don't delete** branch after that.

**Review by kens-aais — APPROVED** [review]

**Comment by kens-aais** [comment]
Done.  Tagged with 0.0.1

From: Rajkishor Sahu ***@***.***>
Date: Friday, August 6, 2021 at 12:07 AM
To: openidl-org/openidl-main ***@***.***>
Cc: Ken Sayers ***@***.***>, Mention ***@***.***>
Subject: Re: [openidl-org/openidl-main] UI migrated to Angular Material and Latest Angular version 12 (#21)

@kens-aais<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkens-aais&data=04%7C01%7Ckens%40aaisonline.com%7C45adb96a7824440d5dc808d958a07953%7C11a183b0e7574f328f598d8dd716cade%7C0%7C0%7C637638268523978998%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2G0x5gHSw%2BdrkVqupLbz5fukLQ90geHPKFNA3jJlktQ%3D&reserved=0> merge it into develop and please don't delete branch after that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopenidl-org%2Fopenidl-main%2Fpull%2F21%23issuecomment-894024728&data=04%7C01%7Ckens%40aaisonline.com%7C45adb96a7824440d5dc808d958a07953%7C11a183b0e7574f328f598d8dd716cade%7C0%7C0%7C637638268523978998%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dlJWG9P2sPDiVUzhxHQygHVKfA4qi9%2BniJGBfiYSBmM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS2JRURGUKIIA33TGIJSHDLT3N32DANCNFSM5BM43OYA&data=04%7C01%7Ckens%40aaisonline.com%7C45adb96a7824440d5dc808d958a07953%7C11a183b0e7574f328f598d8dd716cade%7C0%7C0%7C637638268523988954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6Yr2F2Ob01W7U3uElroa%2FH1sGctEPu6o%2BN0L7uSBWmk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckens%40aaisonline.com%7C45adb96a7824440d5dc808d958a07953%7C11a183b0e7574f328f598d8dd716cade%7C0%7C0%7C637638268523988954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jgtU6zKL5RISynb9g7aFysuaGsVyWIeYs0656IpAK9o%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ckens%40aaisonline.com%7C45adb96a7824440d5dc808d958a07953%7C11a183b0e7574f328f598d8dd716cade%7C0%7C0%7C637638268523998909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g9iaRyG%2FqLs6yH%2Ff5gc6XDFuQDkoroWaB%2Fn%2FZsjtTck%3D&reserved=0>.

**Pull request merged**
