### PR TITLE
Unittest insurancedatamanager

### PR DESCRIPTION
**Pull request by charyitpc**
@kens-aais ,
Could you please review and approve the PR.

Please Note: 
insurance-data-handler.js line# 25, 
I am unable to mock direct DB calls. Since DBManagerFactory object is constructed as part of import (JS Hoisting).

### CODE REVIEW

**Comment by charyitpc** [comment]
image

**Comment by kens-aais** [comment]
Chary,

Is there some docs i can use to learn how to run these locally?
Maybe and update to the readme?

Ken

**Comment by charyitpc** [comment]
Hi @kens-aais , 
Its just a simple step. Once you have the latest code.
1. npm install
2. npm run jest
It will run all unit test cases and shows result in console. 
We can view detailed coverage report in this file. 
openid-insurance-data-manager/coverage/lcov-report/index.html
 Note: coverage folder is added to .gitignore

**Comment by kens-aais** [comment]
That is what i figured.  I get the error about the ${GITHUB_TOKEN} what did you do about that?
________________________________

**Comment by kens-aais** [comment]
That did not work.  I still get the same error message.
________________________________

**Comment by charyitpc** [comment]
@kens-aais , 
Can we have a short call to check on it. Please let me know your availability.

**Pull request merged**
