### PR TITLE
Node v8 to v14

### PR DESCRIPTION
**Pull request by charyitpc**
Hi Ken / Sandeep, 

I made below changes as part of node js migration from v8 to v14. Backend Node API changes for below repos 
```
openidl-common-lib
openidl-data-call-app
openidl-data-call-mood-listener
openidl-data-call-processor
openidl-insurance-data-manager
openidl-transactional-data-event-listener
openidl-utilities
```
1. Updated Node engine in package.json => 
"engines": {
        "node": "14.17.x",
        "npm": "6.14.x"
    },
2. audit fixes => SemVer fixes and Manual fixes (Fabric update I have not done.)
3. Removed IBM Github dependencies in package.jsons
4. published openidl-common-lib@0.1.2 to GITHUB Packages [https://github.com/openidl-org/openidl-main/packages/889689]
5. Update all package.json using @openidl-org/openidl-common-lib
6. Update all the code which uses require('openidl-common-lib');
7. Fixed code after upgrading log4js
8. Updated Dockerfile to use node 14 on the image.
9. Created scripts to generate the localDockerImages

### CODE REVIEW

**Comment by kens-aais** [comment]
So this has already been merged with develop and tested through minikube?
Also, we don't want to merge directly into main.  The merge should be from your branch into develop.

**Comment by charyitpc** [comment]
@kens-aais , 
I was intending to raise PR for develop, sorry I didn't notice it was pointing to master. I edited the PR. Thank you.

**Comment by kens-aais** [comment]
All commits should have referenced #10 in their message.
What is the best way to test this?  I assume it still uses the IBM Cloud so I can just put the secrets in the right place and run?
Or do I need to build the local images and then test from those?

**Comment by kens-aais** [comment]
I tried to run the main script and ran into some errors.
Do I need to update my npm / node before running it?
We must update the readme to remove the references to 8.9 of node and add how to run this script.

**Comment by kens-aais** [comment]
Version 15 of node is out now. 
How do we keep up with the latest?

**Pull request closed without merging**
